excluded:
 - Pods
 - Versal/Resources/R.generated.swift

opt_in_rules:
 - capture_variable
 - closure_body_length
 - closure_end_indentation
 - closure_spacing
 - collection_alignment
 - contains_over_filter_count
 - contains_over_filter_is_empty
 - contains_over_first_not_nil
 - contains_over_range_nil_comparison
 - convenience_type
 - discarded_notification_center_observer
 - discouraged_assert
 - discouraged_none_name
 - discouraged_object_literal
# - discouraged_optional_boolean
 - empty_count
 - empty_string
 - empty_xctest_method
# - explicit_acl
 - explicit_init
 - explicit_self
# - explicit_top_level_acl
# - explicit_type_interface
 - extension_access_modifier
 - fallthrough
 - fatal_error_message
 - file_name_no_space
 - first_where
 - flatmap_over_map_reduce
# - force_unwrapping
 - function_default_parameter_at_end
# - ibinspectable_in_extension
 - identical_operands
# - implicit_return
 - last_where
 - legacy_multiple
 - legacy_objc_type
 - let_var_whitespace
 - literal_expression_end_indentation
 - lower_acl_than_parent
 - modifier_order
 - multiline_arguments
 - multiline_function_chains
 - multiline_parameters
 - nimble_operator
# - no_grouping_extension
 - nslocalizedstring_key
 - nslocalizedstring_require_bundle
 - number_separator
 - operator_usage_whitespace
 - overridden_super_call
 - override_in_extension
 - prefer_nimble
 - prefer_self_in_static_references
 - prefer_self_type_over_type_of_self
 - prefer_zero_over_explicit_init
# - prefixed_toplevel_constant
 - private_action
 - private_outlet
 - private_subject
 - prohibited_super_call
 - quick_discouraged_call
 - quick_discouraged_focused_test
 - quick_discouraged_pending_test
 - reduce_into
 - redundant_nil_coalescing
 - redundant_type_annotation
 - single_test_class
 - sorted_first_last
 - sorted_imports
 - static_operator
 - strong_iboutlet
 - test_case_accessibility
 - toggle_bool
# - type_contents_order
 - unavailable_function
 - unneeded_parentheses_in_closure_argument
 - unowned_variable_capture
 - untyped_error_in_catch
 - unused_declaration
 - unused_import
 - vertical_parameter_alignment_on_call
 - vertical_whitespace_closing_braces
 - vertical_whitespace_opening_braces
 - weak_delegate
 - xct_specific_matcher
 - yoda_condition

closure_body_length: 30
identifier_name:
  allowed_symbols: ["_"]
  excluded: ["db","DB","get","i","id","L10N","no","set","t","x","y"]
large_tuple: 10
line_length: 180
number_separator:
  minimum_length: 5
