# https://docs.fastlane.tools/actions

opt_out_usage
# update_fastlane
skip_docs
default_platform(:ios)

platform :ios do
  lane :increment_build do
    increment_build_number_in_xcodeproj()
  end

  lane :increment_major do
    increment_version_number_in_xcodeproj(
      bump_type: 'major',
      scheme: 'Development'
    )
  end

  lane :increment_minor do
    increment_version_number_in_xcodeproj(
      bump_type: 'minor',
      scheme: 'Development'
    )
  end

  lane :increment_patch do
    increment_version_number_in_xcodeproj(
      bump_type: 'patch',
      scheme: 'Development'
    )
  end

  lane :tests do
    run_tests(clean: true,
              code_coverage: true,
              devices: ["iPhone 13"],
              output_types: 'junit',
              scheme: "Development", 
              xcodebuild_formatter: 'xcbeautify --quiet'
              )
  end
end